I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/CaveScene1.rpy", line 1641, in script
    E "2!" with vpucnh
  File "game/CaveScene1.rpy", line 1641, in <module>
    E "2!" with vpucnh
NameError: name 'vpucnh' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/CaveScene1.rpy", line 1641, in script
    E "2!" with vpucnh
  File "renpy/ast.py", line 714, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "renpy/ast.py", line 538, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/CaveScene1.rpy", line 1641, in <module>
    E "2!" with vpucnh
NameError: name 'vpucnh' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.3.1414
 
Tue Apr  6 14:19:26 2021
